---
title: "ISTA 321 Midterm Project"
author: "Graham I. Gordon, James Coyle, Alyssa Ortega"
date: "2025-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\
```{r init}
library(tidyverse)
library(ggplot2)
library(conflicted)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
```

```{r wine}
redWine <- tibble(read.csv('/Users/giggabite/Library/Mobile Documents/com~apple~CloudDocs/MyCode/Data Science/Data 321/wine+quality/winequality-red.csv',sep=';'))

colnames(redWine) <- c('fix_acid','voli_acid','cit_acid','sugar','Cl','free_SO2','total_SO2','density','pH','sulfates','alcohol','quality')


whiteWine <- tibble(read.csv('/Users/giggabite/Library/Mobile Documents/com~apple~CloudDocs/MyCode/Data Science/Data 321/wine+quality/winequality-white.csv',sep=';'))

colnames(whiteWine) <- c('fix_acid','voli_acid','cit_acid','sugar','Cl','free_SO2','total_SO2','density','pH','sulfates','alcohol','quality')
```

```{r, covMaps}
covMap <- function(data){
  # Creates correlation matrix of numeric data and organizes it 
  # for ggplot to use ( X Y Cor ), where X and Y are var names
  # and cor is the correlation of each variable combination
  covData <- select(data, where(is.numeric)) %>% cor() %>% 
    as_tibble(rownames = 'X') %>% 
    pivot_longer( -X,names_to='Y', values_to='correlation')
  
  varNames <- colnames(data)
  covData <- mutate(covData,
                   X = factor(X, levels = varNames),
                   Y = factor(Y, levels = rev(varNames)))
  
  
  ggplot(covData, aes(X,Y)) + 
    geom_tile(aes(fill=correlation), color = 'black') +
    geom_text(aes(label = round(correlation, 2)), size = 2.5, 
              fontface = 'bold'
              ) +
    theme_minimal(
      base_size = 12, 
    ) + 
    labs(
      x = element_blank(),
      y = element_blank(),
      fill = 'Correlation',
      base_family = 'Times New Roman',
      title = paste0(deparse(substitute(data)), ' Correlation')
    ) + 
    scale_fill_gradient2(
      high = 'green4',
      mid = 'white',
      low = 'dodgerblue4',
      limits = c(-1,1),
      midpoint = 0
    ) + 
    coord_cartesian( expand = FALSE ) + 
    theme( axis.text.x = element_text(angle = 45, hjust = 1))
}

covMap(redWine)
covMap(whiteWine)
  


```

```{r histograms}
# Define colors for vertical lines
line.data <- data.frame(xintercept = c(mean(redWine$quality), mean(3:8)), 
                        Lines = c(paste0("Random \nMean\n",mean(3:8),'\n'),
                                  paste0("Sample \nMean\n",round(mean(redWine$quality),1),'\n')),
                        color = c("red", "blue"), stringsAsFactors = FALSE)

ggplot(data=redWine, aes(x=quality)) + 
  geom_histogram(binwidth=1) + 
  geom_vline(aes(xintercept=xintercept, color = Lines), line.data) + 
  scale_colour_manual(values = line.data$color) + 
  labs(
    title = 'Red Wine'
    )

line.data2 <- data.frame(xintercept = c(mean(whiteWine$quality), mean(3:8)), 
                        Lines = c(paste0("Random \nMean\n",mean(3:8),'\n'),
                                  paste0("Sample \nMean\n",round(mean(whiteWine$quality),1),'\n')),
                        color = c("red", "blue"), stringsAsFactors = FALSE)

ggplot(whiteWine, aes(x=quality)) + 
  geom_histogram(binwidth=1) + 
  geom_vline(aes(xintercept=xintercept, color = Lines), line.data2) + 
  scale_colour_manual(values = line.data$color) + 
  labs(
    title = 'White Wine'
    ) 
  
```


```{r ttest/anova}
# Tests to quanitify similarity btw sample means and random means
t.test(x=redWine$quality, mu = mean(3:8))
t.test(x=whiteWine$quality, mu = mean(3:8))

aovmod_red <- aov(alcohol~quality, data = redWine)
aovmod_white <- aov(alcohol~quality, data = whiteWine)

plot(aovmod_red)
plot(aovmod_white)

bartlett.test(alcohol~quality, data = redWine)
bartlett.test(alcohol~quality, data = whiteWine)

summary(aovmod_red)
summary(aovmod_white)

oneway.test(alcohol~quality, data = redWine)
oneway.test(alcohol~quality, data = whiteWine)
```


```{r}
#Creates a model for wine quality based on chemical variables
full_formula <- quality ~ density + voli_acid +
  sugar + pH + sulfates + alcohol
#Apply the model to the white wine data
lm_full <- lm(full_formula, data = redWine)

#find r squared value
r_squared <- summary(lm_full)$r.squared

#the below line calculates the strength of the model/effect size
f2 <- r_squared / (1 - r_squared)
summary(f2)
summary(lm_full)
```


```{r}
#The next seven lines are the same as the above model but applied to the red wine data
full_formula <- quality ~ density + voli_acid +
  sugar + pH + sulfates + alcohol

lm_full2 <- lm(full_formula, data = whiteWine)
r_squared <- summary(lm_full2)$r.squared
f2 <- r_squared / (1 - r_squared)
summary(f2)
summary(lm_full2)
```

```{r}
#These are the chemical variables we wanted to plot against wine quality
feat <- c("alcohol", "voli_acid", "density", "sulfates", "sugar", "pH")

#This reshapes the data on red wine so it is easier to plot
plot_df <- redWine %>%
  select(quality, all_of(feat)) %>%
  pivot_longer(-quality, names_to = "feature", values_to = "value")

#The code below creates a scatterplot with a trend line for each chemcial variable
ggplot(plot_df, aes(value, quality)) +
  geom_point(alpha = 0.15, size = 1) +   #This was necessary for less overlap between the plotted points
  
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ feature, scales = "free_x", ncol = 3) +  #show plots individually based on chemical variable
  labs(title = "How Chemistry Relates to Red Wine Quality",  #Necessary labels for clear visualization
       x = "Feature value", y = "Quality (3–8)") +
  theme_minimal(base_size = 13) 
```

```{r}
#The same chemcial variables chosen for the red wine
feat <- c("alcohol", "voli_acid", "density", "sulfates", "sugar", "pH")

#Again pivot longer was used to reshape the data in an attempt to make it easier to plot
plot_df <- whiteWine %>%
  select(quality, all_of(feat)) %>%
  pivot_longer(-quality, names_to = "feature", values_to = "value")

#Creation of a scatter plot similar to the one seen above, but instead applies to white wine
ggplot(plot_df, aes(value, quality)) +
  geom_point(alpha = 0.15, size = 1) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ feature, scales = "free_x", ncol = 3) +
  labs(title = "How Chemistry Relates to White Wine Quality",
       x = "Feature value", y = "Quality (3-8)") +
  theme_minimal(base_size = 13) + 
  theme(panel.spacing = unit(1.5, "lines"))   #For some reason there was an overlap of axis labels between plots so the panel spacing was used to combat that 
```







