---
title: "Midterm"
author: "Alyssa"
date: "2025-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
## Load libraries
library(ggplot2)
library(tidyverse)
library(dplyr)
library(cowplot)


## Data Exploration for Red Wine Dataset
head(winequality.red)
glimpse(winequality.red)
glimpse(winequality.white)
summary(winequality.red)
str(winequality.red)

## Does the type of wine (red or white) influence the relationship between these properties and quality?

winequality.red$type <- "red"
winequality.white$type <- "white"

#combine both data sets
red_and_white <- rbind(winequality.red, winequality.white)

head(red_and_white)

#check how many red and white wine types there are
table(red_and_white$type)

red_and_white$type <- as.factor(red_and_white$type)

## Exploring the Data
p1 <- ggplot(winequality.red, aes(x = alcohol)) + geom_histogram() + labs(title = "Red Wine Alcohol")
p2 <- ggplot(winequality.white, aes(x = alcohol)) + geom_histogram() + labs(title = "White Wine Alcohol")
p3 <- ggplot(winequality.red, aes(x = residual.sugar)) + geom_histogram() + labs(title = "Red Wine Residual Sugar")
p4 <- ggplot(winequality.white, aes(x = residual.sugar)) + geom_histogram() + labs(title = "White Wine Residual Sugar")

plot_grid(p1, p2, p3, p4)

## Research question: Does alcohol content relate to wine quality, and does that relationship differ between red and white wines?

## Single predictor linear regression model
single_predictor_lm <- lm(quality ~ alcohol * type, data = red_and_white)
single_predictor_lm
summary(single_predictor_lm)

single_predictor_lm_2 <- lm(quality ~ residual.sugar, data = red_and_white)
single_predictor_lm_2
summary(single_predictor_lm_2)



## View the attributes of single_predictor_lm
attributes(single_predictor_lm)

## Residuals are just about symmetric around 0 making our model valid
single_predictor_lm$residuals
hist(single_predictor_lm$residuals)

## Build lm chart
red_and_white %>% 
  ggplot(aes(alcohol, quality, color = type)) +
  geom_point() +
  geom_smooth(method = lm, se = F) +
  theme_bw() +
  labs(title = "Red and White Wine Quality Based on Alcohol Content",
       x = "Alcohol Level",
       y = "Wine Quality",
       color = "Wine Type")


## Multi Linear Regression
multi_predictor_lm <- lm(quality ~ alcohol + residual.sugar * type, data = red_and_white)
multi_predictor_lm
summary(multi_predictor_lm)

multi_predictor_lm_2 <- lm(quality ~ residual.sugar * type, data = red_and_white)
multi_predictor_lm_2
summary(multi_predictor_lm_2)

red_wine_single_lm <- lm(quality ~ alcohol, data = winequality.red)
summary(red_wine_single_lm)

red_wine_single_lm %>% 
  ggplot(aes(alcohol, quality)) +
  geom_point() +
  geom_smooth(method = lm, se = F) +
  theme_bw() +
  labs(title = "Red Wine Quality Based on Alcohol Content",
       x = "Alcohol Level",
       y = "Wine Quality",
       color = "Wine Type")

## Take a sample of the white whine dataset and then make an interaction with red wine

## Check which type of wine has the minimun number of datapoints
min_red_white <- min(table(red_and_white$type))
min_red_white


## Create a sample of the red_and_white data set to make the red and white equal number
set.seed(123)

sample <- red_and_white %>%
  group_by(type) %>%
  slice_sample(n = min_red_white) %>%
  ungroup()

## Confirm they are equal
table(sample$type)

## Updated Linear model for our sample dataset
sample_lm <- lm(quality ~ alcohol * type, data = sample)
summary(sample_lm)

sample %>%
  ggplot(aes(alcohol, quality, color = type)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = lm, se = FALSE) +
  theme_bw() +
  labs(title = "Balanced Comparison: Red vs White Wine Quality by Alcohol",
       x = "Alcohol Level",
       y = "Wine Quality")

plot(sample_lm)


```

